INSERT INTO public.tools (id,name,description,category,icon,from_type,to_type,popular,enabled,tool_type) VALUES
('loan-emi','EMI Calculator','Calculate loan EMI, interest & total payment instantly','finance','Calculator','Loan','EMI',true,true,'finance'),
('mortgage-calculator','Mortgage Calculator','Estimate full mortgage PITI: principal, interest, tax & insurance','finance','Calculator','Home','PITI',true,true,'finance'),
('home-loan-emi','Home Loan EMI Calculator','Calculate home loan EMI with total interest & repayment','finance','Calculator','Loan','EMI',true,true,'finance'),
('car-loan-emi','Car Loan EMI Calculator','Auto loan monthly payment calculator','finance','Calculator','Loan','EMI',false,true,'finance'),
('personal-loan-emi','Personal Loan EMI Calculator','Personal loan EMI & total interest calculator','finance','Calculator','Loan','EMI',false,true,'finance'),
('student-loan-calculator','Student Loan Calculator','Calculate student loan monthly payments & interest','finance','Calculator','Loan','EMI',false,true,'finance'),
('credit-card-payoff','Credit Card Payoff Calculator','Find how fast you can pay off credit card debt','finance','Calculator','Balance','Months',true,true,'finance'),
('credit-card-min-payment','Credit Card Min Payment Calculator','Calculate minimum payment & true payoff time','finance','Calculator','Balance','Min Pay',false,true,'finance'),
('simple-interest','Simple Interest Calculator','Calculate simple interest on principal','finance','Calculator','Principal','Interest',true,true,'finance'),
('compound-interest','Compound Interest Calculator','Calculate compound interest & future value','finance','Calculator','Principal','Future Value',true,true,'finance'),
('apr-calculator','APR Calculator','Calculate true Annual Percentage Rate with fees','finance','Calculator','Loan','APR',false,true,'finance'),
('apy-calculator','APY Calculator','Calculate Annual Percentage Yield from nominal rate','finance','Calculator','APR','APY',false,true,'finance'),
('cagr-calculator','CAGR Calculator','Compound Annual Growth Rate calculator','finance','Calculator','Returns','CAGR',true,true,'finance'),
('roi-calculator','ROI Calculator','Return on Investment calculator with profit','finance','Calculator','Investment','ROI',true,true,'finance'),
('irr-calculator','IRR Calculator','Internal Rate of Return from cash flows','finance','Calculator','Cash Flows','IRR',false,true,'finance'),
('npv-calculator','NPV Calculator','Net Present Value from cash flow stream','finance','Calculator','Cash Flows','NPV',false,true,'finance'),
('fd-calculator','FD Calculator','Fixed Deposit maturity & interest calculator','finance','Calculator','Deposit','Maturity',true,true,'finance'),
('rd-calculator','RD Calculator','Recurring Deposit maturity calculator','finance','Calculator','Monthly','Maturity',false,true,'finance'),
('ppf-calculator','PPF Calculator','Public Provident Fund 15-year maturity calculator','finance','Calculator','Deposit','Maturity',false,true,'finance'),
('sip-calculator','SIP Calculator','Mutual Fund SIP future value & wealth gain','finance','Calculator','Monthly','Future Value',true,true,'finance'),
('lumpsum-calculator','Lumpsum Calculator','One-time investment future value calculator','finance','Calculator','Lumpsum','Future Value',false,true,'finance'),
('mutual-fund-returns','Mutual Fund Returns Calculator','Track mutual fund profit/loss from NAV','finance','Calculator','NAV','Returns',false,true,'finance'),
('swp-calculator','SWP Calculator','Systematic Withdrawal Plan remaining corpus','finance','Calculator','Corpus','Withdrawal',false,true,'finance'),
('step-up-sip','Step-up SIP Calculator','SIP with yearly increment future value','finance','Calculator','SIP','Future Value',false,true,'finance'),
('nps-calculator','NPS Calculator','National Pension Scheme corpus & pension','finance','Calculator','Contribution','Pension',false,true,'finance'),
('epf-calculator','EPF Calculator','Employee Provident Fund maturity calculator','finance','Calculator','Salary','EPF',false,true,'finance'),
('gratuity-calculator','Gratuity Calculator','End-of-service gratuity payment calculator','finance','Calculator','Salary','Gratuity',false,true,'finance'),
('retirement-corpus','Retirement Corpus Calculator','How much you need to retire comfortably','finance','Calculator','Expense','Corpus',true,true,'finance'),
('inflation-calculator','Inflation Calculator','See future cost & buying power of money','finance','Calculator','Today','Future',false,true,'finance'),
('future-value','Future Value Calculator','Calculate future value of money over time','finance','Calculator','PV','FV',false,true,'finance'),
('present-value','Present Value Calculator','Discount future cash to today''s value','finance','Calculator','FV','PV',false,true,'finance'),
('annuity-calculator','Annuity Calculator','Annuity present value & future value','finance','Calculator','Payment','PV/FV',false,true,'finance'),
('perpetuity-calculator','Perpetuity Calculator','Calculate present value of perpetual cash flow','finance','Calculator','Cash Flow','PV',false,true,'finance'),
('bond-price','Bond Price Calculator','Calculate fair bond price from YTM','finance','Calculator','YTM','Price',false,true,'finance'),
('bond-yield','Bond Yield Calculator','Current yield from coupon & price','finance','Calculator','Price','Yield',false,true,'finance'),
('ytm-calculator','YTM Calculator','Yield to Maturity approximate calculator','finance','Calculator','Bond','YTM',false,true,'finance'),
('dividend-yield','Dividend Yield Calculator','Calculate stock dividend yield percentage','finance','Calculator','Dividend','Yield',false,true,'finance'),
('dividend-discount-model','Dividend Discount Model Calculator','Gordon Growth Model fair price of stock','finance','Calculator','Dividend','Price',false,true,'finance'),
('stock-profit','Stock Profit Calculator','Calculate stock trade profit, loss & return','finance','Calculator','Trade','P&L',true,true,'finance'),
('stock-average','Stock Average Calculator','Calculate average buy price after multiple buys','finance','Calculator','Buys','Average',false,true,'finance'),
('stock-target-price','Stock Target Price Calculator','Target price from EPS and PE multiple','finance','Calculator','EPS','Target',false,true,'finance'),
('pe-ratio','P/E Ratio Calculator','Price to Earnings ratio of a stock','finance','Calculator','Price/EPS','PE',false,true,'finance'),
('pb-ratio','P/B Ratio Calculator','Price to Book ratio calculator','finance','Calculator','Price/Book','PB',false,true,'finance'),
('eps-calculator','EPS Calculator','Earnings Per Share calculator','finance','Calculator','Income','EPS',false,true,'finance'),
('market-cap','Market Cap Calculator','Calculate company market capitalization','finance','Calculator','Shares','Cap',false,true,'finance'),
('book-value','Book Value Per Share Calculator','Equity book value per share calculator','finance','Calculator','Equity','BVPS',false,true,'finance'),
('debt-to-equity','Debt to Equity Ratio Calculator','D/E ratio leverage calculator','finance','Calculator','Debt','D/E',false,true,'finance'),
('current-ratio','Current Ratio Calculator','Liquidity current ratio calculator','finance','Calculator','CA/CL','Ratio',false,true,'finance'),
('quick-ratio','Quick Ratio Calculator','Acid-test quick ratio liquidity calculator','finance','Calculator','Assets','Quick',false,true,'finance'),
('working-capital','Working Capital Calculator','Net working capital calculator','finance','Calculator','CA−CL','WC',false,true,'finance'),
('gross-margin','Gross Margin Calculator','Gross profit margin percentage','finance','Calculator','Rev−COGS','Margin',false,true,'finance'),
('operating-margin','Operating Margin Calculator','Operating profit margin percentage','finance','Calculator','OpInc/Rev','Margin',false,true,'finance'),
('net-margin','Net Profit Margin Calculator','Net profit margin percentage','finance','Calculator','NI/Rev','Margin',false,true,'finance'),
('break-even','Break-Even Calculator','Break-even units & revenue calculator','finance','Calculator','Costs','BE Units',true,true,'finance'),
('markup-calculator','Markup Calculator','Selling price from cost and markup','finance','Calculator','Cost','Price',false,true,'finance'),
('discount-calculator','Discount Calculator','Sale price and savings calculator','finance','Calculator','Price','Final',true,true,'finance'),
('tip-calculator','Tip Calculator','Restaurant tip & bill split calculator','finance','Calculator','Bill','Tip',true,true,'finance'),
('sales-tax','Sales Tax Calculator','Sales tax & total amount calculator','finance','Calculator','Amount','Tax',false,true,'finance'),
('vat-calculator','VAT Calculator','Value Added Tax calculator','finance','Calculator','Amount','VAT',false,true,'finance'),
('gst-calculator','GST Calculator','GST add or remove calculator','finance','Calculator','Amount','GST',true,true,'finance'),
('income-tax-india','Income Tax Calculator India','Indian income tax (new regime FY24-25)','finance','Calculator','Income','Tax',true,true,'finance'),
('income-tax-us','Income Tax Calculator USA','US federal income tax 2024 brackets','finance','Calculator','Income','Tax',false,true,'finance'),
('capital-gains-tax','Capital Gains Tax Calculator','Capital gains tax on trade calculator','finance','Calculator','Gain','Tax',false,true,'finance'),
('paycheck-calculator','Paycheck Calculator','Net pay after federal, state & FICA','finance','Calculator','Gross','Net',true,true,'finance'),
('salary-hike','Salary Hike Calculator','Calculate salary hike percentage','finance','Calculator','Old/New','Hike',false,true,'finance'),
('hourly-to-salary','Hourly to Salary Calculator','Convert hourly wage to annual salary','finance','Calculator','Hourly','Salary',false,true,'finance'),
('salary-to-hourly','Salary to Hourly Calculator','Convert annual salary to hourly rate','finance','Calculator','Salary','Hourly',false,true,'finance')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,category=EXCLUDED.category,from_type=EXCLUDED.from_type,to_type=EXCLUDED.to_type,popular=EXCLUDED.popular,enabled=true,tool_type=EXCLUDED.tool_type;