INSERT INTO public.tools (id,name,description,category,icon,from_type,to_type,popular,enabled,tool_type) VALUES
('overtime-pay','Overtime Pay Calculator','Calculate overtime wage with multiplier','finance','Calculator','Hours','OT Pay',false,true,'finance'),
('take-home-salary','Take-Home Salary Calculator','In-hand salary after PF & tax deductions','finance','Calculator','CTC','In-Hand',true,true,'finance'),
('tax-bracket-us','US Tax Bracket Calculator','Find your marginal US tax bracket','finance','Calculator','Income','Bracket',false,true,'finance'),
('social-security-tax','Social Security Tax Calculator','Social Security tax (6.2%) calculator','finance','Calculator','Wage','SS Tax',false,true,'finance'),
('medicare-tax','Medicare Tax Calculator','Medicare tax with additional 0.9% threshold','finance','Calculator','Wage','Tax',false,true,'finance'),
('fica-calculator','FICA Tax Calculator','FICA: Social Security + Medicare calculator','finance','Calculator','Wage','FICA',false,true,'finance'),
('self-employment-tax','Self-Employment Tax Calculator','SE tax (15.3%) for freelancers calculator','finance','Calculator','Net Inc','SE Tax',false,true,'finance'),
('property-tax','Property Tax Calculator','Annual property tax calculator','finance','Calculator','Value','Tax',false,true,'finance'),
('rent-vs-buy','Rent vs Buy Calculator','Compare renting vs buying a home','finance','Calculator','Rent/Buy','Verdict',true,true,'finance'),
('rental-yield','Rental Yield Calculator','Gross rental yield percentage calculator','finance','Calculator','Rent','Yield',false,true,'finance'),
('cap-rate','Cap Rate Calculator','Real estate capitalization rate calculator','finance','Calculator','NOI','Cap Rate',false,true,'finance'),
('cash-on-cash-return','Cash-on-Cash Return Calculator','Real estate cash-on-cash ROI calculator','finance','Calculator','Cash','CoC',false,true,'finance'),
('gross-rent-multiplier','Gross Rent Multiplier Calculator','GRM real estate valuation calculator','finance','Calculator','Price','GRM',false,true,'finance'),
('mortgage-refinance','Mortgage Refinance Calculator','Refinance savings & break-even calculator','finance','Calculator','Old/New','Savings',false,true,'finance'),
('loan-prepayment','Loan Prepayment Calculator','Extra payment payoff time saver','finance','Calculator','Extra','Months Saved',false,true,'finance'),
('loan-amortization','Loan Amortization Calculator','EMI, year-1 interest & total interest calculator','finance','Calculator','Loan','Schedule',false,true,'finance'),
('debt-snowball','Debt Snowball Calculator','Smallest-balance-first payoff strategy','finance','Calculator','Debts','Order',false,true,'finance'),
('debt-avalanche','Debt Avalanche Calculator','Highest-APR-first payoff strategy','finance','Calculator','Debts','Order',false,true,'finance'),
('debt-to-income','Debt-to-Income Ratio Calculator','DTI ratio for loan approvals','finance','Calculator','Debt/Income','DTI',false,true,'finance'),
('savings-goal','Savings Goal Calculator','Monthly saving needed to hit a goal','finance','Calculator','Goal','Monthly',true,true,'finance'),
('emergency-fund','Emergency Fund Calculator','Recommended emergency fund target','finance','Calculator','Expense','Target',false,true,'finance'),
('millionaire-calculator','Millionaire Calculator','Years to reach 1 million dollars','finance','Calculator','Save','Years',false,true,'finance'),
('coast-fire','Coast FIRE Calculator','Coast FIRE number for early retirement','finance','Calculator','Expense','Coast',false,true,'finance'),
('fire-number','FIRE Number Calculator','Financial Independence target (25× rule)','finance','Calculator','Expense','FIRE',false,true,'finance'),
('currency-converter','Currency Converter Calculator','Manual currency converter with custom rate','finance','Calculator','Currency','Currency',false,true,'finance'),
('currency-strength','Currency Strength Calculator','Calculate % change between FX rates','finance','Calculator','Rates','Change',false,true,'finance'),
('cryptocurrency-profit','Cryptocurrency Profit Calculator','Crypto trade profit, loss & return calculator','finance','Calculator','Trade','P&L',true,true,'finance'),
('crypto-staking-rewards','Crypto Staking Rewards Calculator','Estimate staking APY rewards','finance','Calculator','Stake','Rewards',false,true,'finance'),
('tax-deduction','Tax Deduction Savings Calculator','Tax saved from a deduction','finance','Calculator','Deduction','Saved',false,true,'finance'),
('payroll-deduction','Payroll Deduction Calculator','Pre-tax payroll deduction calculator','finance','Calculator','Gross','Taxable',false,true,'finance'),
('tip-split','Tip Split Calculator','Split bill, tip & per-person share','finance','Calculator','Bill','Split',false,true,'finance'),
('cost-of-living-adjustment','Cost of Living Adjustment Calculator','COLA salary adjustment from CPI','finance','Calculator','Salary','COLA',false,true,'finance'),
('inflation-adjusted-return','Inflation-Adjusted Return Calculator','Real return after inflation calculator','finance','Calculator','Nominal','Real',false,true,'finance')
ON CONFLICT (id) DO UPDATE SET name=EXCLUDED.name,description=EXCLUDED.description,category=EXCLUDED.category,from_type=EXCLUDED.from_type,to_type=EXCLUDED.to_type,popular=EXCLUDED.popular,enabled=true,tool_type=EXCLUDED.tool_type;